<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!-- This is a ROS package file, intended to allow this library to be built
     side-by-side to ROS packages in a catkin/ament environment.
-->
<package format="3">
  <name>mola_glim_wrapper</name>
  <version>0.1.0</version>
  <description>MOLA wrapper for the GLIM LiDAR-inertial odometry algorithm</description>

  <maintainer email="joseluisblancoc@gmail.com">Jose-Luis Blanco-Claraco</maintainer>
  <license>GPLv3</license>

  <url type="repository">https://github.com/MOLAorg/mola_glim_wrapper/</url>

  <!-- core dependencies -->
  <depend>mola_common</depend>
  <depend>mola_kernel</depend>
  <depend>mola_yaml</depend>

  <depend>mrpt_libtclap</depend>
  <depend>mrpt_libmaps</depend>
  <depend>mrpt_libobs</depend>

  <depend>eigen</depend>
  <depend>gtsam</depend>
  <depend>libboost-dev</depend>
  <depend>libspdlog-dev</depend>

  <!-- dataset input sources (all are actually optional) -->
  <depend>mola_input_mulran_dataset</depend>
  <depend>mola_input_rosbag2</depend>
  <depend>mola_input_rosbag1</depend>
  <depend>mola_input_rawlog</depend>
  <depend>mola_input_kitti_dataset</depend>

  <!-- Entries to make ROS 2 to discover this as a proper package -->
  <build_depend>ros_environment</build_depend>
  <build_depend>ament_cmake_xmllint</build_depend>

  <buildtool_depend>cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_gtest</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_lint_cmake</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <!-- Needed by the mola-glim-gui-* scripts: -->
  <exec_depend>mola_launcher</exec_depend>
  <exec_depend>mola_viz</exec_depend>
  <exec_depend>mola_viz_imgui</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
